services:
    CleverAge\EAVManager\AkeneoProductBundle\Context\AkeneoContextManager:
        autowire: true
        calls:
            - [setLocale, ['%eav_manager.akeneo_product.default.locale%']]
            - [setScope, ['%eav_manager.akeneo_product.default.channel%']]
            - [setSelectAttributeLabelProvider, ['@CleverAge\EAVManager\AkeneoProductBundle\Provider\Attribute\AttributeSelectLabelProvider']]

    eav_manager.akeneo.manager.context: '@CleverAge\EAVManager\AkeneoProductBundle\Context\AkeneoContextManager'