services:
    CleverAge\EAVManager\AkeneoProductBundle\Context\AkeneoContextManager:
        autowire: true
        arguments:
            $locale: '%eav_manager.akeneo_product.default.locale%'
            $scope: '%eav_manager.akeneo_product.default.channel%'
        calls:
            - [setSelectAttributeLabelProvider, ['@CleverAge\EAVManager\AkeneoProductBundle\Provider\Attribute\AttributeSelectLabelProvider']]

    eav_manager.akeneo.manager.context: '@CleverAge\EAVManager\AkeneoProductBundle\Context\AkeneoContextManager'